---
date: '2017-06-20'
draft: true
title: Brandenburgs Wasser Daten in einer Shiny App
description: "Shiny Apps auf shinyapps.io" 
author: 'Tobias Recke'
type: "blog"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>  


### Die App

>In Brandenburg werden die Wasserstands- und Durchfluss-Messungen verschiedener Pegel vom Landesamt für Umwelt Brandenburg im UmweltInformationssystem Brandenburg (LUIS-BB) bereitgestellt. Sie können beispielsweise von den nachfolgenden Links bezogen werden.  

>+      Die Durchfluss-Daten gibt es:  1. <a href="http://www.luis.brandenburg.de/w/hwmz/frankfurt/oder/pegel/W7100014/" target="_blank">hier</a>,  2. <a href="http://www.luis.brandenburg.de/w/hwmz/potsdam/mittlere%5Felbe/pegel/W7100009/" target="_blank">hier</a>, und 3. <a href="http://www.luis.brandenburg.de/w/hwmz/cottbus/pegel/W7100056/Default.aspx" target="_blank">hier</a>.  
>+      Die Wasserstands-Daten stammen von: 1. <a href="http://www.luis.brandenburg.de/w/hwmz/potsdam/mittlere%5Felbe/pegel/W7100008/" target="_blank">hier</a>, 2. <a href="http://www.luis.brandenburg.de/w/hwmz/cottbus/pegel/W7100047/Default.aspx" target="_blank">hier</a>, und 3. <a href="http://www.luis.brandenburg.de/w/hwmz/frankfurt/oder/pegel/W7100015/" target="_blank">hier</a>.  
  
>Den Links können Rohdaten, gemessen um 06:00 Uhr in der Früh, entnommen werden. Das LUIS-BB stellt die Daten der vergangenen sechs Tage online bereit und weißt zugleich darauf hin, dass solche Rohdaten nicht für hydrologische Modelle geeignet sind. Dennoch kann beispielsweise mit einer Shiny-App den Daten ein Wenig Farbe verliehen werden! Ein paar simple Plots helfen dabei, die Oberflächengewässer eines der wasserreichsten deutschen Bundesländer (Brandenburg hat rd. 3.000 Seen und über 30.000 Kilometer Flüsse und Bäche <a href="http://www.bund-brandenburg.de/themen_projekte/wasser/" target="_blank">(BUND, 2017)</a>) quantitativ etwas näher zu beleuchten.  
In der App können über eine Checkbox bis zu 35 Monitoring-Stationen ausgewählt werden. Die Variablen Wasserstand [cm] und Durchfluss  [m³/s] lassen sich anschließend als Zeitreihen abbilden und mittels deskriptiver Statistik beschreiben.

<br>  

### Link zur Seite
>Wer die Seite einmal besuchen möchte: <a href="https://meine.shinyapps.io/bwater/" target="_blank">hier ist der Link zur Anwendung</a>.

<br>

### Anmerkunken 
>Es sei angemerkt:

>1.  *Eine Shiny Anwendung ist eine Internetseite mit Benutzeroberfläche (engl. ui, user interface) die mit einem Computer verbunden ist, auf dem eine aktive R-Session läuft (engl. server). Anwender können die Benutzeroberfläche anpassen. Der Server führt dann R-Quellcode aus, der die Bildschirmanzeige der Benutzeroberfläche aktualisiert* <a href="https://www.rstudio.com/wp-content/uploads/2015/08/shiny-german.pdf" target="_blank">(RStudio, 2017).</a>
2.  Die App befindet sich auf einem Server von RStudio und wird unter einem kostenlosen Konto geführt, deshalb ist die Seite in der Summe nur 25 Stunden im Monat erreichbar. Es kann vorkommen, dass gen Ende eines Monats die Seite nicht zur Verfügung steht.
3.  In der App wird als Dezimal-Trennzeichen anstatt eines Kommas ein Punkt verwendet - generell verwendet die Programmiersprache R als Dezimaltrennzeichen den Punkt. 
    